config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'
  resources :users do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  Gutentag::ActiveRecord.call self
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  def tags_as_string
    tag_names.join(", ")
  end

  def tags_as_string=(string)
    self.tag_names = string.split(/,\s*/)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post
  validates :name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params['search'].present?
      return @posts = Post
                 .where("title LIKE ?", "%#{params['search']}%")
                 .or(Post.where("body LIKE ?", "%#{params['search']}%"))
    end
    if params['tag'].present?
      return @posts = Post.tagged_with(:names => params['tag'].split(/,\s*/))
    end
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(:user_id => params[:user_id])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    set_post
  end

  # GET /posts/new
  def new
    require_user
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    require_user
    set_post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = params[:user_id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to [current_user, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    require_user
    set_post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [current_user, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    require_user
    set_post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to [current_user, @post], notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :tags_as_string)
    end

    def require_user
      @user = User.find_by_id(params[:user_id])
      redirect_to '/404.html' if @user.nil? or !current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<% if (params.has_key?(:search)) %>
  <h1>Search results for "<%= params[:search] %>"</h1>
<% elsif (params.has_key?(:tag)) %>
  <h1>Tagged "<%= params[:tag] %>"</h1>
<% else %>
  <h1>Latests Posts</h1>
<% end %>
<% if (@posts.each do |post| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to post.title, user_post_path(post.user, post) %></h5>
        <p class="card-subtitle mb-2 text-muted"><%= post.user.name %></p>
        <p class="card-text"><%= post.body %></p>
      </div>
    </div>
  <% end).empty? %>
  There are no posts
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <p class="navbar-text">
    <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </p>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="nav navbar-nav ">
      <% if user_signed_in? %>
        <li class="dropdown nav-item">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span id="user-name"><%= current_user.name %></span>
            <span class="caret"></span>
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Posts', user_posts_path(current_user), :class => 'dropdown-item' %>
            <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'dropdown-item' %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'nav-item ml-2 mr-2' %></li> |
        <li><%= link_to "Login", new_user_session_path, :class => 'nav-item ml-2' %></li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [current_user, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :tags_as_string, 'Tags (separated by comma)' %>
    <%= form.text_field :tags_as_string %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', user_post_path(@post.user, @post) %> |
<%= link_to 'Back', user_posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', user_post_path(post.user, post) %></td>
        <% if current_user == post.user %>
          <td><%= link_to 'Edit', edit_user_post_path(post.user, post) %></td>
          <td><%= link_to 'Destroy', user_post_path(post.user, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_user_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Tags:</strong>
  <% @post.tag_names.each do |tag| %>
    <span class="badge"><%= link_to tag, "/?tag=#{tag}" %></span>
  <% end %>
</p>
<% if current_user == @post.user %>
  <%= link_to 'Edit', edit_user_post_path(@post.user, @post) %> |
<% end %>
<%= link_to 'Back', '/' %>